version: "3"

vars:
  AIVEN_WEB_URL: '{{.AIVEN_WEB_URL|default "https://api.aiven.io"}}'

tasks:
  curlSpec:
    requires:
      vars:
        - AIVEN_WEB_URL
    cmds:
      - curl -so service_types.json {{.AIVEN_WEB_URL}}/v1/service_types
  curlSpecSensitive:
    requires:
      vars:
        - AIVEN_TOKEN
        - AIVEN_PROJECT_NAME
        - AIVEN_WEB_URL
    cmds:
      - for: [integration_types, integration_endpoint_types]
        cmd: 'curl -so {{.ITEM}}.json {{.AIVEN_WEB_URL}}/v1/project/{{.AIVEN_PROJECT_NAME}}/{{.ITEM}} --header "Authorization: aivenv1 {{.AIVEN_TOKEN}}"'
    silent: true
  generate:
    cmds:
      - go run main.go service_types.json integration_types.json integration_endpoint_types.json
  run:
    deps:
      - curlSpec
      - curlSpecSensitive
    cmds:
      - task: generate
  build:
    cmds:
      - go build
  test:
    cmds:
      - go test -v ./...
  curlDist:
    desc: During the development, the diff might change multiple times. Downloads files from main
    cmds:
      - for: [service_types, integration_types, integration_endpoint_types]
        cmd: "curl -so ./pkg/dist/{{.ITEM}}.yml https://raw.githubusercontent.com/aiven/go-api-schemas/refs/heads/main/pkg/dist/{{.ITEM}}.yml"
  fmt-imports:
    desc: Remove blank lines in Go import blocks and run goimports
    cmds:
      - find . -type f -name '*.go' -exec sed -i'' -e '/^import ($/,/^)$/{/^[[:space:]]*$/d;}' {} +
      - goimports -local "github.com/aiven/go-api-schemas" -w .
  fmt:
    desc: Format code
    cmds:
      - task: fmt-imports
