// Package diffMaps is the package that contains the diffMaps functionality.
package diff

import (
	"encoding/json"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/stretchr/testify/assert"

	"github.com/aiven/go-api-schemas/internal/pkg/types"
	"github.com/aiven/go-api-schemas/internal/pkg/util"
)

// TestDiff tests the diff functions.
// nolint:funlen,lll // This function is long, but it's a test function.
// // These lines are long, but they're test data.
func TestDiff(t *testing.T) {
	type args struct {
		g map[string]types.UserConfigSchema
		r map[string]types.UserConfigSchema
	}

	tests := []struct {
		name string
		args args
		want map[string]types.UserConfigSchema
	}{
		{
			name: "no read schema",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum:                            nil,
						Minimum:                         util.Ref(0.0),
						Maximum:                         util.Ref(0.0),
						MinLength:                       util.Ref(0),
						MaxLength:                       util.Ref(0),
						MaxItems:                        util.Ref(0),
						CreateOnly:                      false,
						Pattern:                         "",
						Example:                         nil,
						UserError:                       "",
					},
				},
				r: nil,
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties:                      nil,
					Items:                           nil,
					OneOf:                           nil,
					Enum:                            nil,
					Minimum:                         util.Ref(0.0),
					Maximum:                         util.Ref(0.0),
					MinLength:                       util.Ref(0),
					MaxLength:                       util.Ref(0),
					MaxItems:                        util.Ref(0),
					CreateOnly:                      false,
					Pattern:                         "",
					Example:                         nil,
					UserError:                       "",
				},
			},
		},
		{
			name: "equal schemas",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum:                            nil,
						Minimum:                         util.Ref(0.0),
						Maximum:                         util.Ref(0.0),
						MinLength:                       util.Ref(0),
						MaxLength:                       util.Ref(0),
						MaxItems:                        util.Ref(0),
						CreateOnly:                      false,
						Pattern:                         "",
						Example:                         nil,
						UserError:                       "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum:                            nil,
						Minimum:                         util.Ref(0.0),
						Maximum:                         util.Ref(0.0),
						MinLength:                       util.Ref(0),
						MaxLength:                       util.Ref(0),
						MaxItems:                        util.Ref(0),
						CreateOnly:                      false,
						Pattern:                         "",
						Example:                         nil,
						UserError:                       "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties:                      nil,
					Items:                           nil,
					OneOf:                           nil,
					Enum:                            nil,
					Minimum:                         util.Ref(0.0),
					Maximum:                         util.Ref(0.0),
					MinLength:                       util.Ref(0),
					MaxLength:                       util.Ref(0),
					MaxItems:                        util.Ref(0),
					CreateOnly:                      false,
					Pattern:                         "",
					Example:                         nil,
					UserError:                       "",
				},
			},
		},
		{
			name: "different schemas",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "bar",
						Description:                     "bar",
						Type:                            "bar",
						Default:                         "bar",
						Properties: map[string]types.UserConfigSchema{
							"baz": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         util.Ref(0.0),
								Maximum:                         util.Ref(0.0),
								MinLength:                       util.Ref(0),
								MaxLength:                       util.Ref(0),
								MaxItems:                        util.Ref(0),
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items: &types.UserConfigSchema{
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties: map[string]types.UserConfigSchema{
								"qux": {
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items: &types.UserConfigSchema{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf: []types.UserConfigSchema{
											{
												UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
												Title:                           "quux",
												Description:                     "",
												Type:                            nil,
												Default:                         nil,
												Properties:                      nil,
												Items:                           nil,
												OneOf:                           nil,
												Enum:                            nil,
												Minimum:                         util.Ref(0.0),
												Maximum:                         util.Ref(0.0),
												MinLength:                       util.Ref(0),
												MaxLength:                       util.Ref(0),
												MaxItems:                        util.Ref(0),
												CreateOnly:                      false,
												Pattern:                         "",
												Example:                         nil,
												UserError:                       "",
											},
										},
										Enum:       nil,
										Minimum:    util.Ref(0.0),
										Maximum:    util.Ref(0.0),
										MinLength:  util.Ref(0),
										MaxLength:  util.Ref(0),
										MaxItems:   util.Ref(0),
										CreateOnly: false,
										Pattern:    "",
										Example:    nil,
										UserError:  "",
									},
									OneOf:      nil,
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
							},
							Items:      nil,
							OneOf:      nil,
							Enum:       nil,
							Minimum:    util.Ref(0.0),
							Maximum:    util.Ref(0.0),
							MinLength:  util.Ref(0),
							MaxLength:  util.Ref(0),
							MaxItems:   util.Ref(0),
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
						OneOf: nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Value:                           "corge",
							},
						},
						Minimum:    util.Ref(1.0),
						Maximum:    util.Ref(1.0),
						MinLength:  util.Ref(1),
						MaxLength:  util.Ref(1),
						MaxItems:   util.Ref(1),
						CreateOnly: false,
						Pattern:    "bar",
						Example:    "bar",
						UserError:  "bar",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum:                            nil,
						Minimum:                         util.Ref(0.0),
						Maximum:                         util.Ref(0.0),
						MinLength:                       util.Ref(0),
						MaxLength:                       util.Ref(0),
						MaxItems:                        util.Ref(0),
						CreateOnly:                      false,
						Pattern:                         "",
						Example:                         nil,
						UserError:                       "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "bar",
					Description:                     "bar",
					Type:                            "bar",
					Default:                         "bar",
					Properties: map[string]types.UserConfigSchema{
						"baz": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items:                           nil,
							OneOf:                           nil,
							Enum:                            nil,
							Minimum:                         util.Ref(0.0),
							Maximum:                         util.Ref(0.0),
							MinLength:                       util.Ref(0),
							MaxLength:                       util.Ref(0),
							MaxItems:                        util.Ref(0),
							CreateOnly:                      false,
							Pattern:                         "",
							Example:                         nil,
							UserError:                       "",
						},
					},
					Items: &types.UserConfigSchema{
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"qux": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "quux",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
					OneOf: nil,
					Enum: []types.UserConfigSchemaEnumValue{
						{
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Value:                           "corge",
						},
					},
					Minimum:    util.Ref(1.0),
					Maximum:    util.Ref(1.0),
					MinLength:  util.Ref(1),
					MaxLength:  util.Ref(1),
					MaxItems:   util.Ref(1),
					CreateOnly: false,
					Pattern:    "bar",
					Example:    "bar",
					UserError:  "bar",
				},
			},
		},
		{
			name: "gen new property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         util.Ref(0.0),
								Maximum:                         util.Ref(0.0),
								MinLength:                       util.Ref(0),
								MaxLength:                       util.Ref(0),
								MaxItems:                        util.Ref(0),
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
							"baz": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         util.Ref(0.0),
								Maximum:                         util.Ref(0.0),
								MinLength:                       util.Ref(0),
								MaxLength:                       util.Ref(0),
								MaxItems:                        util.Ref(0),
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         util.Ref(0.0),
								Maximum:                         util.Ref(0.0),
								MinLength:                       util.Ref(0),
								MaxLength:                       util.Ref(0),
								MaxItems:                        util.Ref(0),
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items:                           nil,
							OneOf:                           nil,
							Enum:                            nil,
							Minimum:                         util.Ref(0.0),
							Maximum:                         util.Ref(0.0),
							MinLength:                       util.Ref(0),
							MaxLength:                       util.Ref(0),
							MaxItems:                        util.Ref(0),
							CreateOnly:                      false,
							Pattern:                         "",
							Example:                         nil,
							UserError:                       "",
						},
						"baz": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items:                           nil,
							OneOf:                           nil,
							Enum:                            nil,
							Minimum:                         util.Ref(0.0),
							Maximum:                         util.Ref(0.0),
							MinLength:                       util.Ref(0),
							MaxLength:                       util.Ref(0),
							MaxItems:                        util.Ref(0),
							CreateOnly:                      false,
							Pattern:                         "",
							Example:                         nil,
							UserError:                       "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    util.Ref(0.0),
					Maximum:    util.Ref(0.0),
					MinLength:  util.Ref(0),
					MaxLength:  util.Ref(0),
					MaxItems:   util.Ref(0),
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
		},
		{
			name: "read new property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         util.Ref(0.0),
								Maximum:                         util.Ref(0.0),
								MinLength:                       util.Ref(0),
								MaxLength:                       util.Ref(0),
								MaxItems:                        util.Ref(0),
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         util.Ref(0.0),
								Maximum:                         util.Ref(0.0),
								MinLength:                       util.Ref(0),
								MaxLength:                       util.Ref(0),
								MaxItems:                        util.Ref(0),
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
							"baz": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         util.Ref(0.0),
								Maximum:                         util.Ref(0.0),
								MinLength:                       util.Ref(0),
								MaxLength:                       util.Ref(0),
								MaxItems:                        util.Ref(0),
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items:                           nil,
							OneOf:                           nil,
							Enum:                            nil,
							Minimum:                         util.Ref(0.0),
							Maximum:                         util.Ref(0.0),
							MinLength:                       util.Ref(0),
							MaxLength:                       util.Ref(0),
							MaxItems:                        util.Ref(0),
							CreateOnly:                      false,
							Pattern:                         "",
							Example:                         nil,
							UserError:                       "",
						},
						"baz": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{
								IsDeprecated:      true,
								DeprecationNotice: "This property is deprecated.",
							},
							Title:       "",
							Description: "",
							Type:        nil,
							Default:     nil,
							Properties:  nil,
							Items:       nil,
							OneOf:       nil,
							Enum:        nil,
							Minimum:     util.Ref(0.0),
							Maximum:     util.Ref(0.0),
							MinLength:   util.Ref(0),
							MaxLength:   util.Ref(0),
							MaxItems:    util.Ref(0),
							CreateOnly:  false,
							Pattern:     "",
							Example:     nil,
							UserError:   "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    util.Ref(0.0),
					Maximum:    util.Ref(0.0),
					MinLength:  util.Ref(0),
					MaxLength:  util.Ref(0),
					MaxItems:   util.Ref(0),
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
		},
		{
			name: "gen new item property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties: map[string]types.UserConfigSchema{
										"bar": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
										"baz": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Items:      nil,
									OneOf:      nil,
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties: map[string]types.UserConfigSchema{
										"bar": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Items:      nil,
									OneOf:      nil,
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items: &types.UserConfigSchema{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties: map[string]types.UserConfigSchema{
									"bar": {
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         util.Ref(0.0),
										Maximum:                         util.Ref(0.0),
										MinLength:                       util.Ref(0),
										MaxLength:                       util.Ref(0),
										MaxItems:                        util.Ref(0),
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
									"baz": {
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         util.Ref(0.0),
										Maximum:                         util.Ref(0.0),
										MinLength:                       util.Ref(0),
										MaxLength:                       util.Ref(0),
										MaxItems:                        util.Ref(0),
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
								},
								Items:      nil,
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
							OneOf:      nil,
							Enum:       nil,
							Minimum:    util.Ref(0.0),
							Maximum:    util.Ref(0.0),
							MinLength:  util.Ref(0),
							MaxLength:  util.Ref(0),
							MaxItems:   util.Ref(0),
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    util.Ref(0.0),
					Maximum:    util.Ref(0.0),
					MinLength:  util.Ref(0),
					MaxLength:  util.Ref(0),
					MaxItems:   util.Ref(0),
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
		},
		{
			name: "read new item property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties: map[string]types.UserConfigSchema{
										"bar": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Items:      nil,
									OneOf:      nil,
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties: map[string]types.UserConfigSchema{
										"bar": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
										"baz": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Items:      nil,
									OneOf:      nil,
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items: &types.UserConfigSchema{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties: map[string]types.UserConfigSchema{
									"bar": {
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         util.Ref(0.0),
										Maximum:                         util.Ref(0.0),
										MinLength:                       util.Ref(0),
										MaxLength:                       util.Ref(0),
										MaxItems:                        util.Ref(0),
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
									"baz": {
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{
											IsDeprecated:      true,
											DeprecationNotice: "This property is deprecated.",
										},
										Title:       "",
										Description: "",
										Type:        nil,
										Default:     nil,
										Properties:  nil,
										Items:       nil,
										OneOf:       nil,
										Enum:        nil,
										Minimum:     util.Ref(0.0),
										Maximum:     util.Ref(0.0),
										MinLength:   util.Ref(0),
										MaxLength:   util.Ref(0),
										MaxItems:    util.Ref(0),
										CreateOnly:  false,
										Pattern:     "",
										Example:     nil,
										UserError:   "",
									},
								},
								Items:      nil,
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
							OneOf:      nil,
							Enum:       nil,
							Minimum:    util.Ref(0.0),
							Maximum:    util.Ref(0.0),
							MinLength:  util.Ref(0),
							MaxLength:  util.Ref(0),
							MaxItems:   util.Ref(0),
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    util.Ref(0.0),
					Maximum:    util.Ref(0.0),
					MinLength:  util.Ref(0),
					MaxLength:  util.Ref(0),
					MaxItems:   util.Ref(0),
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
		},
		{
			name: "gen new item one of property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "qux",
											Description:                     "",
											Type:                            "string",
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "quux",
											Description:                     "",
											Type:                            "object",
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "qux",
											Description:                     "",
											Type:                            "string",
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items: &types.UserConfigSchema{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf: []types.UserConfigSchema{
									{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "quux",
										Description:                     "",
										Type:                            "object",
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         util.Ref(0.0),
										Maximum:                         util.Ref(0.0),
										MinLength:                       util.Ref(0),
										MaxLength:                       util.Ref(0),
										MaxItems:                        util.Ref(0),
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
									{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "qux",
										Description:                     "",
										Type:                            "string",
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         util.Ref(0.0),
										Maximum:                         util.Ref(0.0),
										MinLength:                       util.Ref(0),
										MaxLength:                       util.Ref(0),
										MaxItems:                        util.Ref(0),
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
								},
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
							OneOf:      nil,
							Enum:       nil,
							Minimum:    util.Ref(0.0),
							Maximum:    util.Ref(0.0),
							MinLength:  util.Ref(0),
							MaxLength:  util.Ref(0),
							MaxItems:   util.Ref(0),
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    util.Ref(0.0),
					Maximum:    util.Ref(0.0),
					MinLength:  util.Ref(0),
					MaxLength:  util.Ref(0),
					MaxItems:   util.Ref(0),
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
		},
		{
			name: "read new item one of property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "qux",
											Description:                     "",
											Type:                            "string",
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "qux",
											Description:                     "",
											Type:                            "string",
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "quux",
											Description:                     "",
											Type:                            "object",
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         util.Ref(0.0),
											Maximum:                         util.Ref(0.0),
											MinLength:                       util.Ref(0),
											MaxLength:                       util.Ref(0),
											MaxItems:                        util.Ref(0),
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    util.Ref(0.0),
									Maximum:    util.Ref(0.0),
									MinLength:  util.Ref(0),
									MaxLength:  util.Ref(0),
									MaxItems:   util.Ref(0),
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items: &types.UserConfigSchema{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf: []types.UserConfigSchema{
									{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{
											IsDeprecated:      true,
											DeprecationNotice: "This item is deprecated.",
										},
										Title:       "quux",
										Description: "",
										Type:        "object",
										Default:     nil,
										Properties:  nil,
										Items:       nil,
										OneOf:       nil,
										Enum:        nil,
										Minimum:     util.Ref(0.0),
										Maximum:     util.Ref(0.0),
										MinLength:   util.Ref(0),
										MaxLength:   util.Ref(0),
										MaxItems:    util.Ref(0),
										CreateOnly:  false,
										Pattern:     "",
										Example:     nil,
										UserError:   "",
									},
									{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "qux",
										Description:                     "",
										Type:                            "string",
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         util.Ref(0.0),
										Maximum:                         util.Ref(0.0),
										MinLength:                       util.Ref(0),
										MaxLength:                       util.Ref(0),
										MaxItems:                        util.Ref(0),
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
								},
								Enum:       nil,
								Minimum:    util.Ref(0.0),
								Maximum:    util.Ref(0.0),
								MinLength:  util.Ref(0),
								MaxLength:  util.Ref(0),
								MaxItems:   util.Ref(0),
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
							OneOf:      nil,
							Enum:       nil,
							Minimum:    util.Ref(0.0),
							Maximum:    util.Ref(0.0),
							MinLength:  util.Ref(0),
							MaxLength:  util.Ref(0),
							MaxItems:   util.Ref(0),
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    util.Ref(0.0),
					Maximum:    util.Ref(0.0),
					MinLength:  util.Ref(0),
					MaxLength:  util.Ref(0),
					MaxItems:   util.Ref(0),
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
		},
		{
			name: "gen new enum value",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{Value: "bar"},
							{Value: "baz"},
						},
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{Value: "bar"},
						},
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties:                      nil,
					Items:                           nil,
					OneOf:                           nil,
					Enum: []types.UserConfigSchemaEnumValue{
						{Value: "bar"},
						{Value: "baz"},
					},
					Minimum:    util.Ref(0.0),
					Maximum:    util.Ref(0.0),
					MinLength:  util.Ref(0),
					MaxLength:  util.Ref(0),
					MaxItems:   util.Ref(0),
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
		},
		{
			name: "read new enum value",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{Value: "bar"},
						},
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{Value: "bar"},
							{Value: "baz"},
						},
						Minimum:    util.Ref(0.0),
						Maximum:    util.Ref(0.0),
						MinLength:  util.Ref(0),
						MaxLength:  util.Ref(0),
						MaxItems:   util.Ref(0),
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties:                      nil,
					Items:                           nil,
					OneOf:                           nil,
					Enum: []types.UserConfigSchemaEnumValue{
						{Value: "bar"},
						{
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{
								IsDeprecated:      true,
								DeprecationNotice: "This value is deprecated.",
							},
							Value: "baz",
						},
					},
					Minimum:    util.Ref(0.0),
					Maximum:    util.Ref(0.0),
					MinLength:  util.Ref(0),
					MaxLength:  util.Ref(0),
					MaxItems:   util.Ref(0),
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := diffMaps(tt.args.r, tt.args.g)
			bGot, _ := json.MarshalIndent(&got, "", "  ")
			bWant, _ := json.MarshalIndent(&tt.want, "", "  ")
			assert.Empty(t, cmp.Diff(bWant, bGot))
		})
	}
}
